[general]
my_url = 'http://ferrit.us'
my_name = 'ferrit!'
my_twitter = 'ferritus'
my_logo = '/assets/img/ferrit-circle.png'

[twitter]
consumer_key = ''
consumer_secret = ''
access_token = ''
access_token_secret = ''

[ferrits]
count = 12
screen_names = [ 'dril', 'dog_rates' ]
hashtags = [ '#ferrets' ]
